### ISSUE TITLE
开放验证平台学习资源文章中的一处错误

### ISSUE THREAD

**Issue by Alexies-he** [XS-MLVP/xs-mlvp.github.io#1]
问题：[开放验证平台学习资源案例一：加法器](https://open-verify.cc/mlvp/docs/quick-start/eg-adder/)中的example.py代码54运行到此会出现报错：`dut.finalize() # 必须显式调用finalize方法，否则会导致内存泄漏，并无法生成波形和覆盖率`，运行到此会出现`File "/xx/MLVP/Adder/picker_out_adder/example.py", line 54, in main
    dut.finalize() # 必须显式调用finalize方法，否则会导致内存泄漏，并无法生成波形和覆盖率
AttributeError: 'DUTAdder' object has no attribute 'finalize'`
解决方法：将54行修改为`dut.Finish()`

**Comment by Miical** [comment]
因为近期picker接口变动较大，所以导致此问题。我们已经在新版文档中更改为了使用新版picker驱动的代码，同时也解决了该问题，后面我们会将新版文档同步至网站，在这期间如果有任何问题可以随时向我们提问，感谢你对我们的关注！

**Comment by Alexies-he** [comment]
期待新版文档
